#!/bin/bash
set -euo pipefail

# Pluribus backup wrapper.
# The Python implementation uses sqlite3.Connection.backup(), validates the
# snapshot with PRAGMA quick_check, compresses it and publishes atomically.

PLURIBUS_ROOT="${PLURIBUS_ROOT:-/opt/pluribus}"
PYTHON_BIN="${PLURIBUS_PYTHON:-$PLURIBUS_ROOT/venv/bin/python}"
STATE_DIR="${PLURIBUS_STATE_DIR:-$PLURIBUS_ROOT/data}"
LOG_FILE="${PLURIBUS_BACKUP_LOG:-$STATE_DIR/backup.log}"
ENV_FILE="${PLURIBUS_ENV_FILE:-$STATE_DIR/pluribus.env}"

umask 077
mkdir -p "$STATE_DIR"

# systemd normally injects this file. For direct cron/manual execution, export
# only the simple PLURIBUS_* KEY=VALUE lines generated by Pluribus itself.
if [ -r "$ENV_FILE" ]; then
    while IFS='=' read -r key value; do
        case "$key" in
            PLURIBUS_*)
                if [[ "$key" =~ ^PLURIBUS_[A-Z0-9_]+$ ]]; then
                    export "$key=$value"
                fi
                ;;
        esac
    done < <(grep -E '^PLURIBUS_[A-Z0-9_]+=' "$ENV_FILE" || true)
fi

{
    echo "[$(date -Is)] Starting Pluribus backup"
    "$PYTHON_BIN" -m pluribus.backup
    echo "[$(date -Is)] Backup complete"
    echo "---"
} >> "$LOG_FILE" 2>&1
